# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: DNSControl-Merge

#
# This workflow applies to any PR that modifies dnsconfig.js or creds.json
#
on:
  push:
    branches: [main]
    paths:
      - "*dnsconfig.js"

permissions:
  contents: read
  pull-requests: write

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: checkout credentials
        env:
          CREDS_JSON: ${{ secrets.CREDS_JSON }}
        run: printf '%s' "$CREDS_JSON" > creds.json
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: dnscontrol push
        uses: DNSControl/dnscontrol-action@71de21213d6a5792e960a03b5b3d61f8530596b8
        with:
          cmdargs: push
          post_pr_comment: true
          post_summary: true
          check: false
