# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# This is a demo of how to use GHA dnscontrol-action for previews.
# Create this file as .github/workflows/pr_preview.yml

name: DNSControl-Preview

#
# This workflow applies to any PR that modifies dnsconfig.js or creds.json
#
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '*dnsconfig.js'

permissions:
  contents: read
  pull-requests: write
  
jobs:
  preview:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      -
        name: dnscontrol preview
        uses: DNSControl/dnscontrol-action@71de21213d6a5792e960a03b5b3d61f8530596b8
        with:
          cmdargs: preview
          post_pr_comment: true
          post_summary: true
          check: true
